stages:
  - generate-child-pipeline
  - execute-child-pipeline

generate-child-pipeline:
  stage: generate-child-pipeline
  script:
    - |
      cat > child-pipeline.yml << EOF
      stages:
        - generate-operators
        - file-mr

      generate-operators:
        stage: generate-operators
        image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
        script:
          - python3 --version
          - wget https://i10git.cs.fau.de/hyteg/hyteg/-/raw/master/.clang-format
          - cd generate
          - virtualenv -p python3 venv
          - source venv/bin/activate
          - GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0="url.https://gitlab-ci-token:${CI_JOB_TOKEN}@i10git.cs.fau.de.insteadOf" GIT_CONFIG_VALUE_0="ssh://git@i10git.cs.fau.de" python -m pip install -r requirements.txt
          - pip freeze
          - rm -rf ../operators/*
          - echo $OPERATOR_BASE_NAME
          - python3 generate.py -o ../operators ../operators-$OPERATOR_BASE_NAME.toml --processes 8
        tags:
          - docker
        parallel:
          matrix:
      EOF
    - |
      for f in operators-*.toml
      do
        OP_NAME=$(echo $f | sed -E 's/operators-(.*)\.toml/\1/')
        cat >> child-pipeline.yml << EOF
              - OPERATOR_BASE_NAME: $OP_NAME
        EOF
  artifacts:
    paths:
      - child-pipeline.yml

execute-child-pipeline:
  stage: execute-child-pipeline
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate-child-pipeline
