hyteg-hfg-integration-test:
  stage: test
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - python3 --version
    - cd generate
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0="url.https://gitlab-ci-token:${CI_JOB_TOKEN}@i10git.cs.fau.de.insteadOf" GIT_CONFIG_VALUE_0="ssh://git@i10git.cs.fau.de" python -m pip install -r requirements.txt
    - pip freeze
    - rm -rf ../operators/*
    - python3 generate.py -o ../operators ../operators.toml
    - cd ..
    - git status
    - git diff --exit-code --stat
  tags:
    - docker
