[[diffusion]]
trial-space   = "P1"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 0
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[diffusion]]
trial-space   = "P1"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 0
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]
blending      = "ParametricP1Map"

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "AnnulusMap"

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [3]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "IcosahedralShellMap"

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "ParametricP2Map"
