[[curl_curl]]
trial-space   = "N1E1"
test-space    = "N1E1"
dimensions    = [3]
quadrature    = 0
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]

[[diffusion]]
trial-space   = "P1"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 0
loop-strategy = "cubes"
optimizations = ["cutloops", "moveconstants", "vectorize"]

[[div_k_grad]]
trial-space   = "P1"
test-space    = "P1"
form-space-args.coefficient_function_space = "P1"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "sym_loc_mat"]

[[div_k_grad]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "sym_loc_mat"]

[[mass]]
trial-space   = "P1"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "sym_loc_mat", "tabulate"]
