[[full_stokes]]
trial-space               = "P2"
test-space                = "P2"
components-trial = [0, 1, 2]
components-test  = [0, 1, 2]
form-space-args.coefficient_function_space = "P2"
dimensions      = [2, 3]
quadrature      = 2
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[full_stokes]]
trial-space               = "P2"
test-space                = "P2"
components-trial = [0, 1]
components-test  = [0, 1]
form-space-args.coefficient_function_space = "P2"
dimensions      = [2]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "AnnulusMap"

[[full_stokes]]
trial-space               = "P2"
test-space                = "P2"
components-trial = [0, 1, 2]
components-test  = [0, 1, 2]
form-space-args.coefficient_function_space = "P2"
dimensions      = [3]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "IcosahedralShellMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [2, 3]
quadrature      = 2
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [2]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "AnnulusMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [3]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "IcosahedralShellMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P1"
dimensions      = [3]
quadrature      = 3
loop-strategy   = "sawtooth"
operator-name   = "FullStokesP1Viscosity"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "IcosahedralShellMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P0"
dimensions      = [3]
quadrature      = 3
loop-strategy   = "sawtooth"
operator-name   = "FullStokesP0Viscosity"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "IcosahedralShellMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P1"
dimensions      = [2, 3]
quadrature      = 2
loop-strategy   = "sawtooth"
operator-name   = "FullStokesP1Viscosity"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "ParametricP2Map"
