[[divergence]]
trial-space   = "P2"
test-space    = "P1"
components-trial = [0, 1, 2]
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[divergence]]
trial-space   = "P2"
test-space    = "P1"
components-trial = [0, 1]
dimensions    = [2]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "AnnulusMap"

[[divergence]]
trial-space   = "P2"
test-space    = "P1"
components-trial = [0, 1, 2]
dimensions    = [3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "IcosahedralShellMap"

[[divergence]]
trial-space   = "P2Vector"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[divergence]]
trial-space   = "P2Vector"
test-space    = "P1"
dimensions    = [2]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "AnnulusMap"

[[divergence]]
trial-space   = "P2Vector"
test-space    = "P1"
dimensions    = [3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "IcosahedralShellMap"
