[[curl_curl]]
trial-space   = "N1E1"
test-space    = "N1E1"
dimensions    = [3]
quadrature    = 0
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]

[[diffusion]]
trial-space   = "P1"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 0
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "AnnulusMap"

[[diffusion]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [3]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "IcosahedralShellMap"

[[div_k_grad]]
trial-space   = "P1"
test-space    = "P1"
form-space-args.coefficient_function_space = "P1"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]

[[div_k_grad]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]

[[div_k_grad]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
blending      = "AnnulusMap"

[[div_k_grad]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [3]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
blending      = "IcosahedralShellMap"

[[mass]]
trial-space   = "P1"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[mass]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2, 3]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]

[[mass]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [2]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
blending      = "AnnulusMap"

[[mass]]
trial-space   = "P2"
test-space    = "P2"
dimensions    = [3]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
blending      = "IcosahedralShellMap"

[[k_mass]]
trial-space   = "P1"
test-space    = "P1"
form-space-args.coefficient_function_space = "P1"
dimensions    = [2, 3]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[k_mass]]
trial-space   = "P1"
test-space    = "P1"
form-space-args.coefficient_function_space = "P1"
dimensions    = [2]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "AnnulusMap"

[[k_mass]]
trial-space   = "P1"
test-space    = "P1"
form-space-args.coefficient_function_space = "P1"
dimensions    = [3]
quadrature    = 3
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "IcosahedralShellMap"

[[k_mass]]
trial-space   = "P2"
test-space    = "P1"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[k_mass]]
trial-space   = "P2"
test-space    = "P1"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "AnnulusMap"

[[k_mass]]
trial-space   = "P2"
test-space    = "P1"
form-space-args.coefficient_function_space = "P2"
dimensions    = [3]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "IcosahedralShellMap"

[[k_mass]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[k_mass]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [2]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "AnnulusMap"

[[k_mass]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.coefficient_function_space = "P2"
dimensions    = [3]
quadrature    = 4
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "IcosahedralShellMap"

[[divergence]]
trial-space   = "P2Vector"
test-space    = "P1"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[divergence]]
trial-space   = "P2Vector"
test-space    = "P1"
dimensions    = [2]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "AnnulusMap"

[[divergence]]
trial-space   = "P2Vector"
test-space    = "P1"
dimensions    = [3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "IcosahedralShellMap"

[[gradient]]
trial-space   = "P1"
test-space    = "P2Vector"
dimensions    = [2, 3]
quadrature    = 2
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize"]

[[gradient]]
trial-space   = "P1"
test-space    = "P2Vector"
dimensions    = [2]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "AnnulusMap"

[[gradient]]
trial-space   = "P1"
test-space    = "P2Vector"
dimensions    = [3]
quadrature    = 2
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize"]
blending      = "IcosahedralShellMap"

[[epsilon]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [2, 3]
quadrature      = 2
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[epsilon]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [2]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "AnnulusMap"

[[epsilon]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [3]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "IcosahedralShellMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [2, 3]
quadrature      = 2
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [2]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "AnnulusMap"

[[full_stokes]]
trial-space               = "P2Vector"
test-space                = "P2Vector"
form-space-args.coefficient_function_space = "P2"
dimensions      = [3]
quadrature      = 3
loop-strategy   = "sawtooth"
optimizations   = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending        = "IcosahedralShellMap"

[[shear_heating]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.viscosity_function_space = "P2"
form-space-args.velocity_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 3
folder-name   = "terraneo"
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]

[[shear_heating]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.viscosity_function_space = "P2"
form-space-args.velocity_function_space = "P2"
dimensions    = [2]
quadrature    = 3
folder-name   = "terraneo"
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
blending      = "AnnulusMap"

[[shear_heating]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.viscosity_function_space = "P2"
form-space-args.velocity_function_space = "P2"
dimensions    = [3]
quadrature    = 3
folder-name   = "terraneo"
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
blending      = "IcosahedralShellMap"

[[grad_rho_by_rho_dot_u]]
trial-space   = "P2Vector"
test-space    = "P1"
form-space-args.density_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 3
operator-name = "FrozenVelocity"
folder-name   = "terraneo"
blending      = "IdentityMap"
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]

[[grad_rho_by_rho_dot_u]]
trial-space   = "P2Vector"
test-space    = "P1"
form-space-args.density_function_space = "P2"
dimensions    = [2]
quadrature    = 3
operator-name = "FrozenVelocity"
folder-name   = "terraneo"
blending      = "AnnulusMap"
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]

[[grad_rho_by_rho_dot_u]]
trial-space   = "P2Vector"
test-space    = "P1"
form-space-args.density_function_space = "P2"
dimensions    = [3]
quadrature    = 3
operator-name = "FrozenVelocity"
folder-name   = "terraneo"
blending      = "IcosahedralShellMap"
loop-strategy = "sawtooth"
optimizations = ["moveconstants", "vectorize", "quadloops"]
