[[advection]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.velocity_function_space = "P2"
dimensions    = [2, 3]
quadrature    = 4
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]

[[advection]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.velocity_function_space = "P2"
dimensions    = [2]
quadrature    = 5
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "AnnulusMap"

[[advection]]
trial-space   = "P2"
test-space    = "P2"
form-space-args.velocity_function_space = "P2"
dimensions    = [3]
quadrature    = 5
loop-strategy = "cubes"
optimizations = ["moveconstants", "vectorize", "quadloops", "tabulate"]
blending      = "IcosahedralShellMap"
